insert into review (author_id, date, content, rate) values (23, '1/31/2023', 'Pro Integer non velit.', 1);
insert into review (author_id, date, content, rate) values (463, '9/11/2023', 'Cra Nunc purus.', 2);
insert into review (author_id, date, content, rate) values (355, '2/13/2023', 'In quis, lectus.', 3);
insert into review (author_id, date, content, rate) values (42, '8/5/2023', 'Proin lonec vitae nisi.', 4);
insert into review (author_id, date, content, rate) values (5, '12/5/2022', 'Lorem iCurabitur convallis.', 5);
insert into review (author_id, date, content, rate) values (12, '10/15/2022', 'Sed sagittis. lectus.', 3);
insert into review (author_id, date, content, rate) values (336, '11/20/2022', 'Proin leo odio nisi.', 2);
insert into review (author_id, date, content, rate) values (54, '9/17/2023', 'Duis aliquam Integer ac neque.', 1);
insert into review (author_id, date, content, rate) values (9, '11/14/2022', 'Aeneondimentum.', 4);
insert into review (author_id, date, content, rate) values (109, '4/23/2023', 'Curabitur at, diam.', 4);
insert into review (author_id, date, content, rate) values (11, '5/16/2023', 'Nam ultrices,at, diam.', 5);
insert into review (author_id, date, content, rate) values (19, '10/9/2022', 'Maecenas utat, lorem.', 4);
insert into review (author_id, date, content, rate) values (213, '3/30/2023', 'In hac habitasse tellus.', 2);
insert into review (author_id, date, content, rate) values (1099, '6/21/2023', 'BBBBBBBB. ', 2);
